import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F7FA',
  },
  loader: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  typingIndicatorContainer: {
    paddingHorizontal: 16,
    paddingVertical: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
  },
  typingIndicatorText: {
    fontSize: 12,
    color: '#6B7280',
    fontStyle: 'italic',
  },
  keyboardView: {
    flex: 1,
  },
  backgroundImage: {
    flex: 1,
    width: '100%',
  },
  listContent: {
    padding: 16,
    paddingTop: 24,
  },
  floatingPill: {
    position: 'absolute',
    right: 16,
    bottom: 16,
    backgroundColor: '#374151',
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    zIndex: 10,
  },
  floatingDateContainer: {
    position: 'absolute',
    top: 10,
    width: '100%',
    alignItems: 'center',
    zIndex: 20,
  },
  floatingDatePill: {
    backgroundColor: 'rgba(235, 239, 243, 0.9)',
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 1,
    elevation: 1,
  },
  floatingDateText: {
    fontSize: 12,
    color: '#4B5563',
    fontWeight: '500',
  },
  unreadBadge: {
    position: 'absolute',
    top: -4,
    left: -4,
    backgroundColor: '#10B981',
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 4,
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  unreadBadgeText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: 'bold',
  },
  // ── Search counter pill ───────────────────────────────────────────────────
  searchCounterPill: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFF7ED',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#FDE68A',
    paddingVertical: 6,
    gap: 16,
  },
  searchNavBtn: {
    padding: 4,
  },
  searchCounterText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#374151',
    minWidth: 52,
    textAlign: 'center',
  },
  // ─────────────────────────────────────────────────────────────────────────
  pinnedBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F6F1ED',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#E5E7EB',
  },
  pinnedIcon: {
    marginRight: 12,
  },
  pinnedTextContainer: {
    flex: 1,
    justifyContent: 'center',
  },
  pinnedSubtitle: {
    fontSize: 14,
    color: '#4A6572',
  },
  pinnedThumbnail: {
    width: 32,
    height: 32,
    borderRadius: 4,
    marginLeft: 12,
  },
  dateHeaderContainer: {
    alignItems: 'center',
    marginVertical: 12,
  },
  dateHeaderPill: {
    backgroundColor: '#ECE5DD',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 1,
    elevation: 1,
  },
  dateHeaderText: {
    fontSize: 12,
    fontWeight: '500',
    color: '#54656F',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  deleteModalContainer: {
    width: '85%',
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 20,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  deleteModalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#111827',
    marginBottom: 20,
  },
  deleteModalButton: {
    paddingVertical: 12,
    alignItems: 'flex-end',
  },
  deleteModalButtonText: {
    fontSize: 16,
    color: '#FF8C00',
    fontWeight: '600',
  }
});
