import { StyleSheet } from 'react-native';
import { Colors, Spacing, Radius, Shadows } from '../design';

export const createStyles = (colors: typeof Colors.light) => StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background.surface },
  header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 16, paddingVertical: 12, backgroundColor: colors.background.surface },
  backButton: { padding: 8 },
  menuButton: { padding: 8 },
  listContent: { paddingBottom: 40 },
  profileSection: { alignItems: "center", paddingTop: 12, paddingBottom: 24 },
  avatarContainer: { position: 'relative' },
  profileImage: { width: 140, height: 140, borderRadius: 70, marginBottom: 16, backgroundColor: colors.background.primary },
  avatarPlaceholder: { justifyContent: "center", alignItems: "center", backgroundColor: colors.brand.primary },
  avatarText: { color: colors.text.inverse, fontSize: 48, fontWeight: "bold" },
  cameraBadge: { position: 'absolute', bottom: 16, right: 0, backgroundColor: colors.brand.primary, width: 36, height: 36, borderRadius: 18, justifyContent: 'center', alignItems: 'center', borderWidth: 3, borderColor: colors.background.surface },
  uploadOverlay: { position: 'absolute', top: 0, left: 0, width: 140, height: 140, borderRadius: 70, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', alignItems: 'center' },
  nameText: { fontSize: 24, fontWeight: "600", color: colors.text.primary, marginBottom: 4 },
  statusText: { fontSize: 16, color: colors.text.secondary },
  actionRow: { flexDirection: "row", justifyContent: "center", gap: 32, marginBottom: 24 },
  actionButton: { alignItems: "center", gap: 8 },
  actionLabel: { fontSize: 14, color: colors.brand.primary, fontWeight: "500" },
  card: { backgroundColor: colors.background.primary, borderRadius: 16, marginHorizontal: 16, marginBottom: 12, padding: 16, ...Shadows.sm },
  sectionTitle: { fontSize: 16, fontWeight: "600", color: colors.text.primary, marginBottom: 8 },
  aboutText: { fontSize: 16, color: colors.text.primary, marginBottom: 4 },
  dateText: { fontSize: 14, color: colors.text.muted },
  menuRow: { flexDirection: "row", alignItems: "center", paddingVertical: 12 },
  menuIconContainer: { width: 40, height: 40, borderRadius: 20, backgroundColor: colors.background.surface, justifyContent: "center", alignItems: "center", marginRight: 16 },
  menuText: { flex: 1, fontSize: 16, color: colors.text.primary },
  menuSubText: { fontSize: 14, color: colors.text.secondary, marginTop: 2 },
  menuBadge: { fontSize: 14, color: colors.text.secondary, marginRight: 12 },
  divider: { height: 1, backgroundColor: colors.background.surface, marginLeft: 56 },
  membersHeaderCard: { backgroundColor: colors.background.primary, marginHorizontal: 16, marginTop: 4, borderTopLeftRadius: 16, borderTopRightRadius: 16, padding: 16, borderBottomWidth: 1, borderBottomColor: colors.background.surface },
  membersHeaderTitle: { fontSize: 16, fontWeight: '600', color: colors.brand.primary },
  memberItem: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.background.primary, paddingHorizontal: 16, paddingVertical: 12, marginHorizontal: 16 },
  memberAvatar: { width: 48, height: 48, borderRadius: 24, marginRight: 12 },
  memberAvatarText: { fontSize: 18, color: colors.text.inverse, fontWeight: 'bold' },
  memberInfo: { flex: 1 },
  memberName: { fontSize: 16, fontWeight: '500', color: colors.text.primary, marginBottom: 2 },
  memberEmail: { fontSize: 14, color: colors.text.secondary },
  adminBadge: { backgroundColor: colors.brand.primaryLight, paddingHorizontal: 8, paddingVertical: 4, borderRadius: 12 },
  adminBadgeText: { color: colors.brand.primary, fontSize: 12, fontWeight: '600' },
  fullScreenContainer: { flex: 1, backgroundColor: '#000000' },
  fullScreenHeader: { flexDirection: 'row', alignItems: 'center', padding: 16 },
  fullScreenBackButton: { paddingRight: 16 },
  fullScreenName: { fontSize: 18, fontWeight: '500', color: '#FFFFFF' },
  fullScreenImageWrapper: { flex: 1, justifyContent: 'center' },
  fullScreenImage: { width: '100%', height: '100%' },
});
