import { StyleSheet, Dimensions } from 'react-native';
import { Colors } from '../design';

const { width } = Dimensions.get('window');

export const createStyles = (colors: typeof Colors.light) => StyleSheet.create({
  micButton: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: colors.bubble.own.background,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 6,
    elevation: 4,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.18,
    shadowRadius: 4,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0,0,0,0.3)',
  },
  sheetContainer: {
    backgroundColor: colors.background.primary,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 24,
    paddingTop: 12,
    paddingBottom: 32,
    alignItems: 'center',
  },
  sheetHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.brand.primary,
    marginBottom: 24,
  },
  middleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    marginBottom: 28,
  },
  timerText: {
    fontSize: 18,
    fontWeight: '600',
    color: colors.text.primary,
    marginRight: 14,
    minWidth: 48,
  },
  waveformContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: 44,
  },
  bar: {
    width: 2.5,
    maxWidth: 3,
    backgroundColor: colors.brand.primary,
    marginHorizontal: 1,
    borderRadius: 1.5,
    minHeight: 4,
  },
  bottomRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  deleteButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: colors.brand.primary + '20',
    justifyContent: 'center',
    alignItems: 'center',
  },
  pauseButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: 56,
    paddingHorizontal: 32,
    borderRadius: 28,
    backgroundColor: colors.brand.primary + '20',
  },
  pauseText: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.brand.primary,
    marginLeft: 8,
  },
  sendButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: colors.brand.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  whatsappOverlay: {
    position: 'absolute',
    left: -280,
    right: 60,
    top: 0,
    bottom: 0,
    borderRadius: 26,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.background.surface,
    zIndex: 50,
  },
  timerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  redDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#EF4444',
  },
  whatsappTimerText: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.text.primary,
  },
  slideCancelContainer: {
    position: 'absolute',
    right: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  slideCancelText: {
    fontSize: 14,
    fontWeight: '500',
    color: colors.text.muted,
  },
  greenMicButton: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: colors.bubble.own.background,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 6,
    elevation: 4,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.18,
    shadowRadius: 4,
  },
  lockWrapper: {
    position: 'absolute',
    right: 0,
    bottom: 56,
    alignItems: 'center',
    width: 50,
    zIndex: 60,
  },
  lockTooltip: {
    backgroundColor: colors.background.surface,
    borderColor: colors.border.primary,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    position: 'absolute',
    right: 56,
    bottom: 24,
    width: 165,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 4,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
  },
  lockTooltipText: {
    color: colors.text.primary,
    fontSize: 12,
    fontWeight: '500',
    textAlign: 'center',
  },
  lockPill: {
    width: 48,
    height: 76,
    borderRadius: 24,
    backgroundColor: colors.background.surface,
    borderColor: colors.border.primary,
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
  },
});