import { StyleSheet } from 'react-native';
import { Colors, Radius, Spacing } from '../design';

export const createStyles = (colors: typeof Colors.light) => StyleSheet.create({
  container: {
    backgroundColor: colors.background.surface,
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "flex-end",
    paddingHorizontal: 10,
    paddingTop: 10,
    paddingBottom: 4,
    backgroundColor: colors.background.surface,
    borderTopWidth: 1,
    borderColor: colors.border.primary,
  },
  iconButton: {
    padding: 8,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 2,
  },
  input: {
    flex: 1,
    marginHorizontal: 8,
    backgroundColor: colors.background.primary,
    borderRadius: Radius.full,
    paddingHorizontal: Spacing.lg,
    paddingTop: 10,
    paddingBottom: 10,
    minHeight: 40,
    maxHeight: 120,
    fontSize: 16,
    color: colors.text.primary,
  },
  sendButton: {
    backgroundColor: colors.brand.primary,
    width: 40,
    height: 40,
    borderRadius: Radius.full,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 4,
    marginLeft: 4,
  },
  replyPreviewContainer: {
    flexDirection: 'row',
    backgroundColor: colors.brand.primaryLight,
    marginHorizontal: Spacing.md,
    marginTop: Spacing.sm,
    borderRadius: Radius.md,
    overflow: 'hidden',
    alignItems: 'center',
  },
  replyPreviewLeftBar: {
    width: 6,
    height: '100%',
    backgroundColor: colors.brand.primary,
    borderTopLeftRadius: Radius.md,
    borderBottomLeftRadius: Radius.md,
  },
  replyPreviewContent: {
    flex: 1,
    paddingVertical: Spacing.sm,
    paddingHorizontal: Spacing.md,
    justifyContent: 'center',
  },
  replyPreviewName: {
    fontSize: 13,
    fontWeight: 'bold',
    color: colors.brand.accent,
    marginBottom: 2,
  },
  replyPreviewText: {
    fontSize: 13,
    color: colors.text.muted,
  },
  replyPreviewThumbnail: {
    width: 36,
    height: 36,
    borderRadius: Radius.sm,
    marginRight: Spacing.sm,
  },
  replyPreviewClose: {
    padding: Spacing.md,
  },
  mentionPopoverContainer: {
    backgroundColor: colors.background.surface,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: colors.border.primary,
    maxHeight: 180,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 5,
  },
  mentionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Spacing.lg,
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border.primary,
  },
  mentionAvatar: {
    width: 32,
    height: 32,
    borderRadius: Radius.full,
    marginRight: Spacing.md,
    backgroundColor: colors.brand.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  mentionAvatarText: {
    color: colors.text.inverse,
    fontSize: 14,
    fontWeight: 'bold',
  },
});