import { StyleSheet } from 'react-native';
import { Colors, Radius, Spacing } from '../design';

export const createStyles = (colors: typeof Colors.light) => StyleSheet.create({
  container: {
    backgroundColor: 'transparent',
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "flex-end",
    paddingHorizontal: 8,
    paddingTop: 6,
    paddingBottom: 6,
    backgroundColor: 'transparent',
    borderTopWidth: 0,
  },
  inputWrapper: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.background.surface,
    borderRadius: Radius.full,
    paddingHorizontal: 6,
    minHeight: 52,
    maxHeight: 130,
    overflow: "hidden",
    elevation: 5,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.18,
    shadowRadius: 6,
  },
  iconButtonInside: {
    padding: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  input: {
    flex: 1,
    paddingHorizontal: 4,
    paddingTop: 10,
    paddingBottom: 10,
    fontSize: 16,
    color: colors.text.primary,
  },
  sendButton: {
    backgroundColor: colors.brand.primary,
    width: 50,
    height: 50,
    borderRadius: 25,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 6,
    elevation: 4,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.18,
    shadowRadius: 4,
  },
  dealInputTagContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: '#F0FDF4',
    borderBottomWidth: 1,
    borderBottomColor: '#DCFCE7',
  },
  dealInputTagText: {
    color: '#059669',
    fontSize: 14,
    fontWeight: '600',
  },
  dealInputTagClose: {
    padding: 2,
  },
  replyPreviewContainer: {
    flexDirection: 'row',
    backgroundColor: colors.brand.primaryLight,
    marginHorizontal: Spacing.md,
    marginTop: Spacing.sm,
    borderRadius: Radius.md,
    overflow: 'hidden',
    alignItems: 'center',
  },
  replyPreviewLeftBar: {
    width: 6,
    height: '100%',
    backgroundColor: colors.brand.primary,
    borderTopLeftRadius: Radius.md,
    borderBottomLeftRadius: Radius.md,
  },
  replyPreviewContent: {
    flex: 1,
    paddingVertical: Spacing.sm,
    paddingHorizontal: Spacing.md,
    justifyContent: 'center',
  },
  replyPreviewName: {
    fontSize: 13,
    fontWeight: 'bold',
    color: colors.brand.accent,
    marginBottom: 2,
  },
  replyPreviewText: {
    fontSize: 13,
    color: colors.text.muted,
  },
  replyPreviewThumbnail: {
    width: 36,
    height: 36,
    borderRadius: Radius.sm,
    marginRight: Spacing.sm,
  },
  replyPreviewClose: {
    padding: Spacing.md,
  },
  mentionPopoverContainer: {
    backgroundColor: colors.background.surface,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: colors.border.primary,
    maxHeight: 180,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 5,
  },
  mentionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Spacing.lg,
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border.primary,
  },
  mentionAvatar: {
    width: 32,
    height: 32,
    borderRadius: Radius.full,
    marginRight: Spacing.md,
    backgroundColor: colors.brand.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  mentionAvatarText: {
    color: colors.text.inverse,
    fontSize: 14,
    fontWeight: 'bold',
  },
});