import { StyleSheet } from 'react-native';
import { Colors, Spacing, Radius, Shadows } from '../../design';

export const createStyles = (colors: typeof Colors.light) => StyleSheet.create({
  bubbleWrapper: {
    width: "100%",
    paddingVertical: 1, 
    // marginBottom: 8,
    marginBottom: Spacing.sm, 
  },
  selectedWrapper: {
    // backgroundColor: "rgba(0,0,0,0.08)", 
    backgroundColor: colors.background.selected,
  },
  messageContainer: {
    maxWidth: "80%",
    marginVertical: 1,
    // paddingHorizontal: 8,
    paddingHorizontal: Spacing.sm,
    // paddingVertical: 4,
    paddingVertical: Spacing.xs,
    // borderRadius: 8,
    borderRadius: Radius.md,
    position: "relative",
  },
  myMessage: {
    alignSelf: "flex-end",
    // backgroundColor: "#F8A871", 
    backgroundColor: colors.brand.bubble,
    borderTopRightRadius: 0,
  },
  otherMessage: {
    alignSelf: "flex-start",
    // backgroundColor: "#FFFFFF",
    backgroundColor: colors.background.surface,
    borderTopLeftRadius: 0,
    // elevation: 1,
    // shadowColor: "#000",
    // shadowOffset: { width: 0, height: 1 },
    // shadowOpacity: 0.1,
    // shadowRadius: 1,
    ...Shadows.sm, // Assuming sm is close to this (elevation 2)
  },
  transparentMessage: {
    backgroundColor: 'transparent',
    elevation: 0,
    shadowOpacity: 0,
    paddingHorizontal: 0,
    paddingVertical: 0,
  },
  myMessageNoTail: {
    // borderTopRightRadius: 8,
    borderTopRightRadius: Radius.md,
  },
  otherMessageNoTail: {
    // borderTopLeftRadius: 8,
    borderTopLeftRadius: Radius.md,
  },
  myTail: {
    position: "absolute",
    right: -10,
    top: 0,
    width: 0,
    height: 0,
    borderTopWidth: 16,
    // borderTopColor: "#F8A871",
    borderTopColor: colors.brand.bubble,
    borderRightWidth: 10,
    borderRightColor: "transparent",
    borderBottomWidth: 0,
    borderLeftWidth: 0,
  },
  otherTail: {
    position: "absolute",
    left: -10,
    top: 0,
    width: 0,
    height: 0,
    borderTopWidth: 16,
    // borderTopColor: "#FFFFFF",
    borderTopColor: colors.background.surface,
    borderLeftWidth: 10,
    borderLeftColor: "transparent",
    borderBottomWidth: 0,
    borderRightWidth: 0,
  },
  forwardedContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 2,
    paddingHorizontal: 2,
  },
  forwardedIcon: {
    marginRight: 4,
  },
  forwardedText: {
    // fontSize: 13,
    // color: '#71828A',
    // fontStyle: 'italic',
    // MOVED to AppText
    fontStyle: 'italic',
  },
  swipeReplyAction: {
    justifyContent: 'center',
    alignItems: 'flex-start',
    // paddingLeft: 16,
    paddingLeft: Spacing.lg,
    width: 80, 
  },
  replyIconCircle: {
    width: 32,
    height: 32,
    // borderRadius: 16,
    borderRadius: Radius.xl, // 16
    // backgroundColor: '#FF8C00',
    backgroundColor: colors.brand.accent,
    justifyContent: 'center',
    alignItems: 'center',
  },
  deletedContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: Spacing.sm,
    paddingHorizontal: Spacing.md,
  },
  deletedIcon: {
    marginRight: Spacing.sm,
  },
  deletedText: {
    fontStyle: 'italic',
    color: colors.text.muted,
  },
  outerRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    width: '100%',
  },
  outerRowMine: {
    justifyContent: 'flex-end',
  },
  outerRowOther: {
    justifyContent: 'flex-start',
  },
  avatarContainer: {
    width: 28,
    height: 28,
    borderRadius: 14,
    marginRight: 6,
    marginTop: 2,
    marginBottom: 2,
    overflow: 'hidden',
  },
  avatarImage: {
    width: 28,
    height: 28,
  },
  avatarPlaceholder: {
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarInitial: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '700',
  },
  senderHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
    paddingBottom: 2,
    gap: 8,
  },
  senderNameText: {
    fontSize: 12.5,
    fontWeight: '700',
    flexShrink: 1,
  },
  senderSubText: {
    fontSize: 11,
    color: '#8696a0',
  },
});